# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15AKILDXQJeLW5cI7emuPvL_I2P22Dg9i
"""

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y
    
def divide(x, y):
    return x / y

def exponent(x, y):
    return x**y

print("Select operation.")
print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")
print("5.Exponent")
print("6.Exit")

while True:
  
        ch= int(input("Enter choice(1/2/3/4/5): "))
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if ch== 1:
            print(num1, "+", num2, "=", add(num1, num2))

        elif ch== 2:
            print(num1, "-", num2, "=", subtract(num1, num2))

        elif ch== 3:
            print(num1, "*", num2, "=", multiply(num1, num2))

        elif ch== 4:
            print(num1, "/", num2, "=", divide(num1, num2))
        elif ch==5:
            print(num1, "**", num2, "=", exponent(num1,num2))
        
        else:
            print("Invalid input")
        
       
        ch = input("Do you want to continue? (y/n): ")
        if ch == "n":
          print("Program exited successfully")
          break